version: '3.8'

services:
  azcon_match_svc:
    image: ghcr.io/aliyeffali7/azcon_match_svc:latest
    container_name: azcon_match_svc
    ports:
      - "8000:8000"
    env_file:
      - /home/ubuntu/azconprice/algorithm/.env
    networks:
      - dev_azconadmin-network
    restart: unless-stopped

networks:
  dev_azconadmin-network:
    external: true

